import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/Footer'
import GameCard from '../components/GameCard'
import NavBar from '../components/NavBar'
import styles from '../styles/Home.module.css'
import gamecardData from '../resources/gamecardData'

export default function Home() {

  const gameCards = gamecardData.cards.map(card => {
    return (
      <GameCard image={card.image} title={card.title} description={card.description}/>
    )
  })

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main>
        <p>
          {`Lorem Ipsum is simply dummy text of the printing and typesetting industry. 
          Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. 
          It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. 
          It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`}
        </p>
        {gameCards}
      </main>
      <Footer />
    </div>
  )
}
